name: Git push to productio

on: push

env:
    OlAksClusterName: ${{ secrets.EJB01OlAksClusterName }}
    OlAksResourceGroup: ${{ secrets.EJB01OlAksResourceGroup }}
    azCliVersion: 2.30.0
    azureACRPassword: ${{ secrets.AZURE_OPEN_LIBERTY_ACR_PASSWORD }}
    azureACRRegistryName: ${{ github.event.inputs.azureACRUserName }}
    azureACRServer: ${{ secrets.EJB01azureACRServer }}
    azureACRUserName: ${{ secrets.EJB01azureACRUserName }}
    azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
    dbName: ${{ secrets.EJB01dbName }}
    dbPassword: ${{ secrets.DB_PASSWORD }}
    dbPortNumber: 5432
    dbServerName: ${{ github.event.inputs.dbName }}.postgres.database.azure.com
    dbType: postgres
    dbUserName: weblogic@${{ github.event.inputs.dbName }}
    location: ${{ github.event.inputs.region }}
    namespace: default
    replicas: 1

jobs:
    deploy-cargo-tracker:
        runs-on: ubuntu-latest
        steps:
            - name: Verify secrets
              run: |
                echo "Verify necessary secrets are set."
                if [ "$EJB01OlAksClusterName == '' ] ; then
                  echo "EJB01OlAksClusterName not set. Exiting."
                  exit 1
                fi
                if [ "$EJB01OlAksResourceGroup == '' ] ; then
                  echo "EJB01OlAksResourceGroup not set. Exiting."
                  exit 1
                fi
                if [ "$EJB01azureACRServer == '' ] ; then
                  echo "EJB01azureACRServer not set. Exiting."
                  exit 1
                fi
                if [ "$EJB01azureACRUserName == '' ] ; then
                  echo "EJB01azureACRUserName not set. Exiting."
                  exit 1
                fi
                if [ "$EJB01dbName == '' ] ; then
                EJB01dbName n echo "Not set. Exiting."
                  exit 1
                fi
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
